include:
  - remote: 'https://gitlab.com/mediacodex/infrastructure/-/raw/master/gitlab/terraform.yml'
  - remote: 'https://gitlab.com/mediacodex/infrastructure/-/raw/master/gitlab/sonarcloud.yml'
  - local: 'docker-ecr.yml'
  - local: 'node-functions.yml'

default:
  image: node:erbium
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - .npm/
      - .terraform/

stages:
  - validate
  - build
  - plan
  - deploy_dev
  - deploy_prod

variables:
  ECR_IMAGE: companies-http
  ECR_REGION: eu-central-1
